#!/bin/bash
#testing read on shell

echo -n "Enter some text > "
read text
echo "You entered: $text"

echo -n "Hurry up and type something! >"
if read -t 3 response; then
	echo "Greate, you made it in time!"
else
	echo "Sorry, you were too slow..."
fi
